plugins {
    id 'java'
    id 'application'
    id 'org.graalvm.buildtools.native' version '0.10.6'
}



repositories {
    mavenCentral()
}

dependencies {
    implementation libs.guava
    implementation 'info.picocli:picocli:4.7.7'

    annotationProcessor 'info.picocli:picocli-codegen:4.7.7'

    testImplementation libs.junit.jupiter
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'com.dieg0407.App'
}

tasks.named('test') {
    useJUnitPlatform()
}

graalvmNative {
    binaries {
        main {
            imageName = 'jcli'
            mainClass = 'com.dieg0407.App'
            debug = false
            verbose = true
        }
    }
}
