#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_MSG=$(cat "$1")

CURRENT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
NEXT_VERSION=$(semver-next --commit-message "$COMMIT_MSG" --last-version "$CURRENT_VERSION")

./mvnw versions:set -DnewVersion="$NEXT_VERSION" -DgenerateBackupPoms=false
git add pom.xml