name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Unit Test
      run: mvn -B package -Dtests=unit --file pom.xml

    - name: Integration Test
      run: mvn test -Dtests=integration --file pom.xml

    - name: Package executable
      run: cd target ; tar czf jcli.tar.gz jcli-*.jar libs

    - name: Release
      uses: softprops/action-gh-release@v1
      if: contains(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.RELEASE_CREATOR_TOKEN }}
        files: |
          target/jcli.tar.gz