name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Unit Test
      run: mvn -B package -Dtests=unit --file pom.xml

    - name: Integration Test
      run: mvn test -Dtests=integration --file pom.xml

    - name: Package executable
      run: cd target ; tar czf jcli.tar.gz jcli-*.jar libs

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: jcli
          path: target/jcli.tar.gz